In [1]:
import pandas as pd
df=pd.read_csv("custdata.tsv", sep="\t")

df.describe()

             custid         income  num.vehicles          age
count  1.000000e+03    1000.000000    944.000000  1000.000000
mean   6.984997e+05   53504.771000      1.916314    51.699815
std    4.135083e+05   65478.065729      1.101618    18.863433
min    2.068000e+03   -8700.000000      0.000000     0.000000
25%    3.456668e+05   14600.000000      1.000000    38.000000
50%    6.934030e+05   35000.000000      2.000000    50.000000
75%    1.044606e+06   67000.000000      2.000000    64.000000
max    1.414286e+06  615000.000000      6.000000   146.680197

In [2]:
df.shape

(1000, 11)

In [3]:
df.isna().sum()

custid            0
sex               0
is.employed     328
income            0
marital.stat      0
health.ins        0
housing.type     56
recent.move      56
num.vehicles     56
age               0
state.of.res      0
dtype: int64

In [4]:
df[['age', 'income', 'num.vehicles']].corr()

                   age    income  num.vehicles
age           1.000000  0.027429     -0.063666
income        0.027429  1.000000      0.139198
num.vehicles -0.063666  0.139198      1.000000

Getting rid of bad data:

Remove rows with ages equal to 0 or over 100 because those ages are unreasonable, remove negative values for income since income is inherently a positive value, for number of vehicles, remove NA's since those should not be included in the overall calculations

In [5]:
df_clean = df[(df["age"]>0) & (df["age"] <= 100)]
df_clean = df_clean[df_clean["income"] >= 0]
df_clean = df_clean.dropna(subset=["num.vehicles"])

In [6]:
df_clean.shape

(932, 11)

1000-932=68 removed data in total

In [7]:
df_clean[['age', 'income', 'num.vehicles']].corr()

                   age    income  num.vehicles
age           1.000000 -0.002644     -0.066295
income       -0.002644  1.000000      0.137859
num.vehicles -0.066295  0.137859      1.000000

There does not appear to be a strong correlation between age, income, and the number of vehicles with the highest correlation being in between number of vehicles and income at 0.138. This isn't a strong enough correlation for a definite relationship with age and income and number of vehicles and age.

Repo Address: https://github.com/KyeSPu/cs82a-portfolio